baseURL = "https://glumes.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Glumes Blog"
theme = "beautifulhugo"

pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
	 useChroma = true



[Author]
	name = "Glumes"
	website = "http://www.glumes.com"
	email = "zhaoying9402@gmail.com"
	github = "glumes"


[taxonomies]
	tag = "tags"
	category = "categories"


[[menu.main]]
	name = "Code"
	weight = 1

[[menu.main]]
	name = "Life"
	weight = 2

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 3



