baseURL = "https://glumes.github.io/"
languageCode = "zh-cn"
DefaultContentLanguage = "en"
title = "Glumes Blog"
theme = "beautifulhugoTheme"

pygmentsUseClasses = false
pygmentCodeFences = true

metaDataFormat = "yaml"

hasCJKLanguage = true


disqusShortname = "glumes"

[Params]
	 useChroma = true
	 commit = false
	 rss = true
	 comments = true

[Author]
	name = "Glumes"
	website = "http://www.glumes.com"
	email = "zhaoying9402@gmail.com"
	github = "glumes"





[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "android"
    url = "categories/android"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "opencv"
    url = "categories/opencv"
    weight = 2


[[menu.main]]
    parent = "Categories"
    name = "opengl"
    url = "categories/opengl"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "ffpmeg"
    url = "categories/ffmpeg"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "python"
    url = "categories/python"
    weight = 5


[[menu.main]]
	identifier = "Tags"
	name = "Tags"
	weight = 2
	url = "tags"


[[menu.main]]
	name = "Life"
	weight = 3

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 4




