baseURL = "https://glumes.github.io/"
languageCode = "zh-cn"
DefaultContentLanguage = "en"
title = "Glumes Blog"
theme = "beautifulhugoTheme"

pygmentsCodeFences = true
pygmentsUseClasses = true

metaDataFormat = "yaml"

hasCJKLanguage = true


disqusShortname = "glumes"

[Params]
	 useChroma = true
	 commit = false
	 rss = true
	 comments = true

[Author]
	name = "Glumes"
	website = "http://www.glumes.com"
	email = "zhaoying9402@gmail.com"
	github = "glumes"




[[menu.main]]
	identifier = "Code"
	name = "Code"
	weight = 1
	url = "tags"


[[menu.main]]
	name = "Life"
	weight = 2

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 3




